# Generated by Django 5.1.7 on 2025-04-01 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('protein_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('pdb_file_path', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_annotation', models.CharField(choices=[('correct', 'Correct'), ('wrong', 'Wrong'), ('unsure', 'Unsure')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='annotations_app.protein')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('protein', 'user')},
            },
        ),
    ]
