# Generated by Django 5.1.7 on 2025-04-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='protein_id',
            field=models.CharField(max_length=100),
        ),
    ]
