# Generated by Django 5.1.7 on 2025-04-02 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations_app', '0002_proteinfolder_protein_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='annotation_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='annotation',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annotations_app.proteinfolder'),
        ),
        migrations.AddField(
            model_name='proteinfolder',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='proteinfolder',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
