# Generated by Django 5.1.7 on 2025-04-29 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations_app', '0003_alter_protein_options_alter_proteinfolder_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protein',
            options={},
        ),
        migrations.AlterModelOptions(
            name='proteinfolder',
            options={},
        ),
        migrations.RemoveField(
            model_name='protein',
            name='domain_csv_path',
        ),
        migrations.AlterField(
            model_name='annotation',
            name='annotation_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annotations_app.proteinfolder'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='pdb_file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='protein_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proteinfolder',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='proteinfolder',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='proteinfolder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DomainCorrection',
        ),
    ]
