# Generated by Django 5.1.7 on 2025-04-29 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations_app', '0004_alter_protein_options_alter_proteinfolder_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protein',
            options={'ordering': ['protein_id']},
        ),
        migrations.AddField(
            model_name='protein',
            name='domain_csv_path',
            field=models.CharField(blank=True, help_text='Path to the domain CSV file within storage, if available.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='name',
            field=models.CharField(blank=True, help_text='Optional display name.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='pdb_file_path',
            field=models.CharField(blank=True, help_text='Path to the PDB file within storage.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='protein_id',
            field=models.CharField(db_index=True, help_text='Unique identifier for the protein (e.g., filename base).', max_length=100),
        ),
        migrations.CreateModel(
            name='DomainCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=100)),
                ('start_pos', models.IntegerField()),
                ('end_pos', models.IntegerField()),
                ('is_marked_wrong', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_corrections', to='annotations_app.protein')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_corrections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
                'unique_together': {('protein', 'user', 'domain_name', 'start_pos', 'end_pos')},
            },
        ),
    ]
