# Generated by Django 5.1.7 on 2025-06-02 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations_app', '0005_alter_protein_options_protein_domain_csv_path_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualDomainAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=100)),
                ('start_pos', models.IntegerField()),
                ('end_pos', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_domain_annotations', to='annotations_app.protein')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_domain_annotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_pos'],
                'unique_together': {('protein', 'user', 'domain_name', 'start_pos', 'end_pos')},
            },
        ),
    ]
