"""
Django settings for annotate_app_project project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_flag(name, default='False'):
    """Read a boolean env var. Tolerates inline '# comments' and 1/yes/on."""
    raw = os.environ.get(name, default).split('#')[0].strip().lower()
    return raw in ('true', '1', 'yes', 'on')


def _env_list(name):
    """Read a comma-separated env var into a list of stripped, non-empty items."""
    raw = os.environ.get(name, '').split('#')[0]
    return [item.strip() for item in raw.split(',') if item.strip()]


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-fallback-key-for-non-docker')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG=True switches this project into "local mode": plaintext HTTP on
# localhost, permissive hosts, and Django serving static/media itself.
DEBUG = _env_flag('DJANGO_DEBUG', 'False')

PRODUCTION_HOSTS = [
    'proteintinder2.bionetic.org', 'www.proteintinder2.bionetic.org',
    'proteintinder.bionetic.org', 'www.proteintinder.bionetic.org',
    'foldswipe.bionetic.org', 'www.foldswipe.bionetic.org',
]

PRODUCTION_ORIGINS = [
    "https://proteintinder2.bionetic.org",
    "http://proteintinder2.bionetic.org",  # add this just in case
    "https://proteintinder.bionetic.org",
    "http://proteintinder.bionetic.org",  # add this just in case
    "https://foldswipe.bionetic.org",
    "http://foldswipe.bionetic.org",  # add this just in case
]

# Extra hosts/origins for whoever is running this, e.g. a LAN IP:
#   DJANGO_ALLOWED_HOSTS=192.168.1.50
#   DJANGO_CSRF_TRUSTED_ORIGINS=http://192.168.1.50:8069
EXTRA_ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS')
EXTRA_CSRF_TRUSTED_ORIGINS = _env_list('DJANGO_CSRF_TRUSTED_ORIGINS')

if DEBUG:
    # Local mode: accept any Host header so localhost, 127.0.0.1 and the
    # machine's LAN IP all work without further configuration.
    ALLOWED_HOSTS = ['*']

    CSRF_TRUSTED_ORIGINS = PRODUCTION_ORIGINS + [
        "http://localhost:8069",
        "http://127.0.0.1:8069",
        "http://localhost:8000",
        "http://127.0.0.1:8000",
    ] + EXTRA_CSRF_TRUSTED_ORIGINS

    # Everything below is HTTPS-only hardening. Leaving it on over plain HTTP
    # would redirect http://localhost:8069 to https:// (which nothing serves),
    # drop the session/CSRF cookies, and pin localhost to HTTPS via HSTS.
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    USE_X_FORWARDED_HOST = False
else:
    ALLOWED_HOSTS = PRODUCTION_HOSTS + EXTRA_ALLOWED_HOSTS
    CSRF_TRUSTED_ORIGINS = PRODUCTION_ORIGINS + EXTRA_CSRF_TRUSTED_ORIGINS

    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # Only if using proxy
    USE_X_FORWARDED_HOST = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'annotations_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'annotate_app_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Add this line to look for templates in BASE_DIR/templates
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True, # Keep this True to also find templates in app directories
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'annotate_app_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.environ.get('DB_NAME', BASE_DIR / 'db.sqlite3'), # Default to SQLite if vars not set
        'USER': os.environ.get('DB_USER'), # No default needed for SQLite
        'PASSWORD': os.environ.get('DB_PASSWORD'), # No default needed for SQLite
        'HOST': os.environ.get('DB_HOST'), # No default needed for SQLite
        'PORT': os.environ.get('DB_PORT'), # No default needed for SQLite
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
         } if os.environ.get('DB_ENGINE') == 'django.db.backends.mysql' else {}, # Only set for MySQL
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Static files (CSS, JavaScript, Images)
# URL to access static files
STATIC_URL = '/static/'

# Directory where collectstatic will place all static files
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Directories to find static files during development
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# === ADD MEDIA FILES CONFIGURATION ===
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media' # Corresponds to /app/media/ in the container

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
